# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotebook', '0003_quote_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user',
            new_name='users',
        ),
    ]
