# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotebook', '0007_auto_20170325_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='users',
        ),
    ]
