# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotebook', '0009_quote_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotebook.User'),
        ),
    ]
