# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Reg',
        ),
    ]
